name: sonar
channels:
  - conda-forge
dependencies:
  - bokeh=2.0.2
  - dask=2.17.2
  - datashader=0.10.0
  - firefox=77.0
  - geckodriver=0.26.0
  - holoviews=1.13.2
  - netcdf4=1.5.3
  - numpy-stl=2.11.2
  - overpy=0.4
  - selenium=3.141.0
  - tzlocal=2.0.0
  - xarray=0.15.1
